import { createApp } from 'vue'
import { createPinia } from 'pinia'

import App from './App.vue'
import router from './router'
import './assets/theme.css'

import 'bootstrap/dist/css/bootstrap.min.css'
import '@coreui/coreui/dist/css/coreui.min.css'

import CoreuiVue from '@coreui/vue'

// Font Awesome
import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

import Toast from 'vue-toastification'
import 'vue-toastification/dist/index.css'

import {
  faGauge,
  faUser,
  faUsers,
  faBars,
  faBell,
  faGem,
  faChartLine,
  faRightFromBracket,
  faChevronRight,
  faFileLines,
  faCalendar,
  faChartBar,
  faGear,
  faSun,
  faMoon,
  faCube,
  faMagnifyingGlass,
  faPlus,
  faTable,
  faPen,
  faTrash,
  faSort,
  faSortUp,
  faSortDown,
  faSpinner,
  faInbox,
  faChevronLeft,
  faCircleUser,
  faCircleInfo,
  faClockRotateLeft,
  faUserPlus,
  faRightToBracket,
  faCheck,
  faPhone,
  faLocationDot,
  faChevronDown,
  faCircle,
  faEnvelope,
  faLock,
  faEye,
  faEyeSlash,
  faEdit,
  faUpload,
  faDownload,
  faSync,
  faList,
  faExclamationTriangle,
  faFileCsv,
  faFileExcel,
  faFilePdf,
  faRotateLeft,
  faTrashCan,
  faCircleLeft,
  faCircleRight,
  faLink,
  faArrowTrendUp,
  faArrowTrendDown,
  faArrowRight,
  faChartPie,
  faShieldHalved,
  faPalette,
  faFloppyDisk,
  faCamera,
  faDesktop,
  faMobileScreen,
  faBan,
  faClock,
  faHome,
  faWindowRestore,
  faCircleQuestion,
  faTerminal,
  faCode,
  faRotate,
  faWandMagicSparkles,
  faArrowLeft,
  faCircleCheck,
  faXmark,
  faTableList,
  faBullseye,
  faWallet,
  faHouse,
  faMapPin,
  faHandshake,
  faHourglassStart,
  faStar,
  faMessage,
  faTasks,
  faUsersBetweenLines,
  faCogs,
  faFolderOpen,
  faServer,
  faUserClock,
  faStore,
  faArrowDownUpAcrossLine,
  faExpand,
  faFileContract,
  faArrowUpRightDots,
  faBarsProgress,
  faLifeRing,
  faNoteSticky,
  faUsersRays,
  faArrowsDownToPeople,
  faArrowsTurnToDots,
  faTty,
  faEllipsis,
  faCircleDot,
  faChartColumn,
  faFile,
  faPaperPlane,
  faBuilding,
  faDatabase,
  faUserCheck,
  faUserXmark,
  faIdCard,
  faCalendarDays,
  faVideo,
  faImage,
  faSignal,
  faMap,
  faMapLocationDot,
  faCircleExclamation,
  faListUl,
  faLayerGroup,
  faFileCircleExclamation,
  faGlobe,
  faTag,
  faCheckDouble,
  faCirclePlus,
  faUserMinus,
  faPeopleArrows,
  faLocationArrow,
  faPhoneVolume,
  faRocket,
  faBuildingUser,
  faSackDollar,
  faCloudArrowUp,
  faSeedling,
  faComments,
  faCircleXmark,
  faFileSignature,
  faMinus,
  faTrophy,
  faFilter,
  faPenToSquare,
  faTimeline,
  faPersonChalkboard,
  faCalendarPlus,
  faBox,
  faClipboardCheck,
  faUserTie,
  faAnglesRight,
  faStopwatch,
  faAnglesLeft,
  faAngleRight,
  faAngleLeft,
  faCalendarDay,
  faBriefcase,
  faGaugeHigh,
  faCloudArrowDown,
  faCalendarCheck,
  faRotateRight,
  faTableCells,
  faIndustry,
  faHourglassHalf,
  faCodeBranch,
  faUpRightFromSquare,
  faMagnifyingGlassMinus,
  faMagnifyingGlassPlus

} from '@fortawesome/free-solid-svg-icons'

library.add(
  faGauge,
  faUser,
  faUsers,
  faBars,
  faBell,
  faGem,
  faChartLine,
  faRightFromBracket,
  faChevronRight,
  faFileLines,
  faCalendar,
  faChartBar,
  faGear,
  faSun,
  faMoon,
  faCube,
  faMagnifyingGlass,
  faPlus,
  faTable,
  faPen,
  faTrash,
  faSort,
  faSortUp,
  faSortDown,
  faSpinner,
  faInbox,
  faChevronLeft,
  faCircleUser,
  faCircleInfo,
  faClockRotateLeft,
  faUserPlus,
  faRightToBracket,
  faCheck,
  faPhone,
  faLocationDot,
  faChevronDown,
  faCircle,
  faEnvelope,
  faLock,
  faEye,
  faEyeSlash,
  faEdit,
  faUpload,
  faDownload,
  faSync,
  faList,
  faExclamationTriangle,
  faFileCsv,
  faFileExcel,
  faFilePdf,
  faRotateLeft,
  faTrashCan,
  faCircleLeft,
  faCircleRight,
  faChartPie,
  faLink,
  faArrowTrendUp,
  faArrowTrendDown,
  faArrowRight,
  faShieldHalved,
  faPalette,
  faFloppyDisk,
  faCamera,
  faDesktop,
  faMobileScreen,
  faBan,
  faClock,
  faHome,
  faWindowRestore,
  faCircleQuestion,
  faTerminal,
  faCode,
  faRotate,
  faWandMagicSparkles,
  faArrowLeft,
  faArrowRight,
  faUserPlus,
  faCircleCheck,
  faXmark,
  faTableList,
  faBullseye,
  faWallet,
  faHouse,
  faMapPin,
  faHandshake,
  faHourglassStart,
  faStar,
  faMessage,
  faTasks,
  faUsersBetweenLines,
  faCogs,
  faFolderOpen,
  faServer,
  faUserClock,
  faStore,
  faArrowDownUpAcrossLine,
  faExpand,
  faFileContract,
  faArrowUpRightDots,
  faBarsProgress,
  faLifeRing,
  faNoteSticky,
  faUsersRays,
  faArrowsDownToPeople,
  faArrowsTurnToDots,
  faTty,
  faEllipsis,
  faCircleDot,
  faChartColumn,
  faFile,
  faPaperPlane,
  faBuilding,
  faDatabase,
  faUserCheck,
  faUserXmark,
  faIdCard,
  faCalendarDays,
  faVideo,
  faImage,
  faSignal,
  faMap,
  faMapLocationDot,
  faCircleExclamation,
  faListUl,
  faLayerGroup,
  faFileCircleExclamation,
  faGlobe,
  faTag,
  faCheckDouble,
  faCirclePlus,
  faUserMinus,
  faPeopleArrows,
  faLocationArrow,
  faPhoneVolume,
  faRocket,
  faBuildingUser,
  faSackDollar,
  faCloudArrowUp,
  faSeedling,
  faComments,
  faCircleXmark,
  faFileSignature,
  faMinus,
  faTrophy,
  faFilter,
  faPenToSquare,
  faTimeline,
  faPersonChalkboard,
  faCalendarPlus,
  faBox,
  faClipboardCheck,
  faUserTie,
  faAnglesRight,
  faStopwatch,
  faAnglesLeft,
  faAngleRight,
  faAngleLeft,
  faCalendarDay,
  faBriefcase,
  faGaugeHigh,
  faCloudArrowDown,
  faCalendarCheck,
  faRotateRight,
  faTableCells,
  faIndustry,
  faHourglassHalf,
  faCodeBranch,
  faUpRightFromSquare,
  faMagnifyingGlassMinus,
  faMagnifyingGlassPlus

)

const app = createApp(App)

const pinia = createPinia()

app.use(pinia)
app.use(router)
app.use(CoreuiVue)

app.component('font-awesome-icon', FontAwesomeIcon)
app.use(Toast, {
  position: 'top-right',
  timeout: 3000,
  closeOnClick: true,
  pauseOnHover: true,
  draggable: true,
  // ← hapus toastDefaults
})

app.mount('#app')